# .github/workflows/python-app.yml

name: Teste em Debian 12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Teste em Debian 12 (Bookworm)
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema (Python, GTK, venv)
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0

      - name: Criar ambiente virtual e instalar dependências Python
        # AQUI ESTÁ A CORREÇÃO: Especificamos que este passo deve usar o shell 'bash'
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Rodar os testes com unittest
        # AQUI TAMBÉM: Usamos 'bash' para garantir que o 'source' funcione
        shell: bash
        run: |
          source .venv/bin/activate
          python -m unittest discover tests
