# .github/workflows/python-app.yml

# Nome do workflow, indicando o ambiente de teste
name: Teste em Debian 12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    # Nome do job para clareza
    name: Teste em Debian 12 (Bookworm)

    # O job vai rodar em uma máquina virtual base do GitHub
    runs-on: ubuntu-latest

    # E DENTRO dessa máquina, vai usar um contêiner do Debian 12
    container:
      image: debian:12 # Usamos a imagem oficial do Debian 12 (Bookworm)

    # Passos a serem executados dentro do contêiner Debian
    steps:
      # 1. Baixar o código do seu repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2. Instalar as dependências do sistema no Debian
      #    - 'apt-get -y' instala sem pedir confirmação
      #    - 'python3-pip' é necessário para o próximo passo
      - name: Instalar dependências (Python, GTK, WebKit)
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0

      # 3. Instalar dependências Python, se houver
      - name: Instalar dependências Python (via pip)
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

      # 4. Rodar os testes
      - name: Rodar os testes com unittest
        run: python3 -m unittest discover tests
